### ISSUE TITLE
Closure conversion

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/kernel#33]
Meta issue for tracking known issues in closure conversion.
- [x] VM assertion error: expected: !is_cycle_free() #38.
- [x] for loops #32.
- [x] capture this.
- [x] static tear-off methods #39.
- [x] super calls #35.
- [x] type variables #36.
- [ ] tear-off methods #34.
- [ ] use VM context and function pointers #37.

**Comment by karlklose** [comment]
This issue was moved to dart-lang/sdk#28126
